[package]
name = "nova-demo"
version = "0.1.0"
edition = "2021"

[dependencies]
nova-scotia = "0.5.0"
nova-snark = "0.23.0"
serde = "1.0.183"
serde_json = "1.0.105"
tokio = { version = "1.32.0", features = ["full"] }